CREATE TABLE USER
(
    USER_ID INT PRIMARY KEY,
    USER_LOGIN_ID VARCHAR(100) NOT NULL,
    USER_PASSWORD VARCHAR(100) NOT NULL,
    USER_NAME VARCHAR(10) NOT NULL,
    USER_PROFILE_IMAGE_PATH VARCHAR(1000) NOT NULL
);

-- CREATE TABLE HOST
-- (
--     HOST_ID INT PRIMARY KEY,
--     HOST_NAME VARCHAR(100) NOT NULL,
--     PROFILE_IMAGE_PATH VARCHAR(1000) NOT NULL
-- );


CREATE TABLE ROOM
(
    ROOM_ID INT PRIMARY KEY, --UNSIGNED?
    HOST_ID INT,
    ROOM_NAME VARCHAR(100) NOT NULL,
    -- ADDRESS VARCHAR(100) NOT NULL, -- (값 타입으로 빼기?)

    PROVINCE VARCHAR(10) NOT NULL, --주소,좌표 묶어서 임베디드타입
    CITY VARCHAR(10) NOT NULL,
    GU VARCHAR(10) NOT NULL, --구는 영어가 없는듯
    COORDINATE VARCHAR(30) NOT NULL,

    PRICE INT NOT NULL,
    DESCRIPTION VARCHAR(300) NOT NULL,
    COMPOSITION VARCHAR(300) NOT NULL, -- 방 구성, 따로 값 타입으로 빼야하는가 (EX. 화장실1개, 침실2개)
    -- 원룸 타입??
    -- CAPACITY INT NOT NULL, --수용인원 (게스트 2명, 유아 1명은 어떻게 표현?)
    GUEST_AMOUNT INT NOT NULL, --AMOUNT 두개 값타입으로 ?
    INFANT_AMOUNT INT NOT NULL,

    FOREIGN KEY(HOST_ID) REFERENCES USER(USER_ID)
);

CREATE TABLE IMAGE
(
    IMAGE_ID INT PRIMARY KEY,
    ROOM_ID INT,
    IMAGE_URL NOT NULL,

    FOREIGN KEY(ROOM_ID) REFERENCES ROOM(ROOM_ID)
);

CREATE TABLE RESERVATION
(
    RESERVATION_ID INT PRIMARY KEY,
    ROOM_ID INT,
    USER_ID INT,
    CHECKIN_DATE DATE NOT NULL, -- 시작날짜, 종료날짜, 값타입으로 빼도 되긴 할듯
    CHECKOUT_DATE DATE NOT NULL,
    -- COMPOSITION_OF_PEOPLE VARCHAR(100) NOT NULL, -- 이것도 고민
    GUEST_AMOUNT INT NOT NULL, -- 어마운트를 임베디드타입으로
    INFANT_AMOUNT INT NOT NULL,
    TOTAL_PRICE INT NOT NULL,

    FOREIGN KEY(ROOM_ID) REFERENCES ROOM(ROOM_ID),
    FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID)
);

CREATE TABLE REVIEW
(
  REVIEW_ID INT PRIMARY KEY,
  ROOM_ID INT,
  USER_ID INT,
  STAR_RATING TINYINT NOT NULL,
  CONTENT TEXT,
  WRITE_DATE DATE NOT NULL,

  FOREIGN KEY(ROOM_ID) REFERENCES ROOM(ROOM_ID),
  FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID)
);

CREATE TABLE WISHLIST
(
    WISHLIST_ID INT PRIMARY KEY,
    USER_ID INT,
    ROOM_ID INT,
    FOREIGN KEY(ROOM_ID) REFERENCES ROOM(ROOM_ID)
);
