
CREATE TABLE USER
(
    USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY ,
    USER_LOGIN_ID VARCHAR(100) NOT NULL,
    USER_PASSWORD VARCHAR(100) NOT NULL,
    USER_NAME VARCHAR(10) NOT NULL,
    USER_PROFILE_IMAGE_PATH VARCHAR(1000) NOT NULL
);

-- CREATE TABLE HOST
-- (
--     HOST_ID INT PRIMARY KEY,
--     HOST_NAME VARCHAR(100) NOT NULL,
--     PROFILE_IMAGE_PATH VARCHAR(1000) NOT NULL
-- );


CREATE TABLE ROOM
(
    ROOM_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    HOST_ID BIGINT,
    ROOM_NAME VARCHAR(100) NOT NULL,

    PROVINCE VARCHAR(10) NOT NULL, -- 주소,좌표 묶어서 임베디드타입
    CITY VARCHAR(10) NOT NULL,
    GU VARCHAR(10) NOT NULL, -- 구는 영어가 없는듯
    COORDINATE VARCHAR(30) NOT NULL,

    PRICE INT NOT NULL,
    DESCRIPTION VARCHAR(300) NOT NULL,
    COMPOSITION VARCHAR(300) NOT NULL, -- 방 구성, 따로 값 타입으로 빼야하는가 (EX. 화장실1개, 침실2개)

    GUEST_AMOUNT INT NOT NULL,
    INFANT_AMOUNT INT NOT NULL,

    FOREIGN KEY(HOST_ID) REFERENCES USER(USER_ID)
);

CREATE TABLE IMAGE
(
    IMAGE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ROOM_ID BIGINT,
    IMAGE_URL VARCHAR(1000) NOT NULL,
    TYPE VARCHAR(10) NOT NULL,
    FOREIGN KEY(ROOM_ID) REFERENCES ROOM(ROOM_ID)
);

CREATE TABLE IF NOT EXISTS airbnb.airbnb_reservation (
    reservation_no BIGINT NOT NULL AUTO_INCREMENT,
    number_of_guest INT NOT NULL DEFAULT 1,
    number_of_infant INT NULL DEFAULT 0,
    price DECIMAL NOT NULL,
    start_at DATE NOT NULL COMMENT '체크인 년,월,일',
    end_at DATE NOT NULL COMMENT '체크아웃 년,월,일',
    user_guest_id BIGINT NOT NULL,
    accomodation_id BIGINT NOT NULL,

    PRIMARY KEY (reservation_no, user_guest_id, accomodation_id),
    INDEX fk_airbnb_reservation_airbnb_user1_idx (user_guest_id ASC) VISIBLE,
    INDEX fk_airbnb_reservation_airbnb_accomodation1_idx (accomodation_id ASC) VISIBLE,
    CONSTRAINT fk_airbnb_reservation_airbnb_user1
    FOREIGN KEY (user_guest_id)
    REFERENCES airbnb.airbnb_user (user_id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT fk_airbnb_reservation_airbnb_accomodation1
    FOREIGN KEY (accomodation_id)
    REFERENCES airbnb.airbnb_accomodation (accomodation_id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;

CREATE TABLE REVIEW
(
    REVIEW_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ROOM_ID BIGINT,
    USER_ID BIGINT,
    STAR_RATING TINYINT NOT NULL,
    CONTENT TEXT,
    WRITE_DATE DATE NOT NULL,

    FOREIGN KEY(ROOM_ID) REFERENCES ROOM(ROOM_ID),
    FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID)
);

CREATE TABLE WISHLIST
(
    WISHLIST_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT,
    ROOM_ID BIGINT,
    FOREIGN KEY(ROOM_ID) REFERENCES ROOM(ROOM_ID)
);
