# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Airbnb' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Airbnb

  target 'AirbnbTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AirbnbUITests' do
    # Pods for testing
  end

  pod 'GoogleMaps', '6.2.1.0'
  pod 'GooglePlaces', '6.2.1.0'
  pod 'SwiftLint'
  pod 'Alamofire', '5.1'
end
